site_name: Duolingo

repo_name: '2019.2-Duolingo'
repo_url: 'https://github.com/Requisitos2-2019/2019.2-Duolingo'

copyright: 'Copyright &copy; 2019 Duolingo'

theme:
  name: 'material'
  language: 'pt'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'green'
    accent: 'light green'
  font:
    text: 'Montserrat'
    code: 'sans-serif'

extra:
  social:
    - type: 'Duolingo'
      link: 'https://www.duolingo.com'

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Início: index.md
  - Planejamento:
    - Metodologia: planejamento/Metodologia.md
    - Heatmap: planejamento/Heatmap.md
    - Roadmap: planejamento/Roadmap.md
    - Pontos de Controle: planejamento/apresentacao.md
  - Pré-Rastriabilidade:
    - Rich Picture: prerastriabilidade/RichPicture.md
  - Elicitação:
    - Análise de Protocolo: elicitacao/AnaliseDeProtocolo.md
    - Brainstorming: elicitacao/Brainstorming.md
    - Entrevista: elicitacao/Entrevista.md
    - Instrospecção: elicitacao/Instrospeccao.md
    - Questionário: elicitacao/Questionario.md
    - Storytelling: elicitacao/Storytelling.md
    - Requisitos Elicitados: elicitacao/RequisitosElicitados.md
  - Modelagem:
    - Cenários: modelagem/Cenarios.md
    - Léxicos: modelagem/Lexicos.md
    - Casos de Uso: modelagem/CasosDeUso.md
    - Especificação Suplementar: modelagem/EspecificacaoSuplementar.md
    - NFR Framework: modelagem/NFR.md
    - Ágil:
      - Backlog do Produto: modelagem/agil/Backlog.md
      - Histórias do Usuários: modelagem/agil/HistoriasDoUsuarios.md
  - Análise:
    - Verificação:
      - Inspeção: analise/verificacao/inspecao.md
      - Backlog do Produto: analise/verificacao/inspecaoBacklog.md
      - Casos de Uso: analise/verificacao/inspecaoCasoDeUso.md
      - Léxicos: analise/verificacao/inspecaoLexico.md
      - Cenários: analise/verificacao/inspecaoCenario.md
      - Especificação Suplementar: analise/verificacao/inspecaoEspecificacao.md
      - NFR Framework: analise/verificacao/inspecaoNFR.md
    - Validação:
      - Comprovação Informal: analise/validacao/comunicacao.md
      - Prototipagem: analise/validacao/prototipo.md
  - Pós-Rastreabilidade:
    - Backward From: posrastreabilidade/BackwardFrom.md
    - Forward From: posrastreabilidade/ForwardFrom.md
